services:
  db:
    image: postgres:17-alpine
    container_name: sanaap_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - sanaap_db_volume_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s


  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    volumes:
      - redis_data_prod:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

  web:
    build: 
      context: .
      dockerfile: dockerfiles/prod/backend/Dockerfile
    container_name: sanaap_backend
    env_file: .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    expose:
      - "8000"
    volumes:
      - static_volume:/usr/src/web/staticfiles
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
  celery:
    build:
      context: .
      dockerfile: dockerfiles/dev/backend/Dockerfile
    container_name: sanaap_celery
    command: celery -A project worker --loglevel=info --concurrency=4
    env_file: .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - ./backend:/usr/src/web
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    expose:
      - "9000"
    ports:
    - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data_prod:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5


  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    env_file: .env
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
        mc mb --ignore-existing local/${MINIO_BUCKET_NAME};
        mc anonymous set none local/${MINIO_BUCKET_NAME};
        echo 'Security Policy Applied to ${MINIO_BUCKET_NAME}';
      "

  nginx:
    build:
      context: ./dockerfiles/prod/nginx/
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/src/web/staticfiles:ro
    depends_on:
      - web
      - minio

volumes:
  minio_data_prod:
  sanaap_db_volume_prod:
  redis_data_prod:
  static_volume: