services:
  db:
    image: postgres:17-alpine
    container_name: sanaap_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - sanaap_db_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s


  web:
    build: 
      context: .
      dockerfile: dockerfiles/dev/backend/Dockerfile
    container_name: sanaap_backend
    env_file: .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    command: bash -c "python manage.py runserver"
    volumes:
      - ./backend:/usr/src/web
    depends_on:
      - db

volumes:
  sanaap_db_volume: