# Generated by Django 6.0.5 on 2026-05-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminrequestmodel',
            options={'verbose_name': 'Admin Request', 'verbose_name_plural': 'Admin Requests'},
        ),
    ]
